# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-26 09:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=30)),
                ('status', models.IntegerField()),
                ('role', models.CharField(max_length=10)),
            ],
        ),
    ]
